package ru.anikanov.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:55:42.057+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.anikanov.ru/", name = "IProjectEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IProjectEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findProjectByPartOfDescriptionRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findProjectByPartOfDescriptionResponse")
    @RequestWrapper(localName = "findProjectByPartOfDescription", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindProjectByPartOfDescription")
    @ResponseWrapper(localName = "findProjectByPartOfDescriptionResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindProjectByPartOfDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.anikanov.tm.api.endpoint.Project findProjectByPartOfDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByFinishDateRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByFinishDateResponse")
    @RequestWrapper(localName = "sortProjectByFinishDate", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByFinishDate")
    @ResponseWrapper(localName = "sortProjectByFinishDateResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByFinishDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.anikanov.tm.api.endpoint.Project> sortProjectByFinishDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/createProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/createProjectResponse")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.CreateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.anikanov.tm.api.endpoint.Project createProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByStartDateRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByStartDateResponse")
    @RequestWrapper(localName = "sortProjectByStartDate", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByStartDate")
    @ResponseWrapper(localName = "sortProjectByStartDateResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByStartDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.anikanov.tm.api.endpoint.Project> sortProjectByStartDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/removeProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/removeProjectResponse")
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveProjectResponse")
    public void removeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findProjectByPartOfNameProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findProjectByPartOfNameProjectResponse")
    @RequestWrapper(localName = "findProjectByPartOfNameProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindProjectByPartOfNameProject")
    @ResponseWrapper(localName = "findProjectByPartOfNameProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindProjectByPartOfNameProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.anikanov.tm.api.endpoint.Project findProjectByPartOfNameProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/updateProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/updateProjectResponse")
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateProjectResponse")
    public void updateProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByStatusRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/sortProjectByStatusResponse")
    @RequestWrapper(localName = "sortProjectByStatus", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByStatus")
    @ResponseWrapper(localName = "sortProjectByStatusResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.SortProjectByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.anikanov.tm.api.endpoint.Project> sortProjectByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findAllProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/findAllProjectResponse")
    @RequestWrapper(localName = "findAllProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindAllProject")
    @ResponseWrapper(localName = "findAllProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindAllProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.anikanov.tm.api.endpoint.Project> findAllProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/removeAllProjectRequest", output = "http://endpoint.api.tm.anikanov.ru/IProjectEndPoint/removeAllProjectResponse")
    @RequestWrapper(localName = "removeAllProject", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveAllProject")
    @ResponseWrapper(localName = "removeAllProjectResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveAllProjectResponse")
    public void removeAllProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
