package ru.anikanov.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-19T18:56:28.508+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.anikanov.ru/", name = "IUserEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/findOneUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/findOneUserResponse")
    @RequestWrapper(localName = "findOneUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindOneUser")
    @ResponseWrapper(localName = "findOneUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindOneUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.anikanov.tm.api.endpoint.User findOneUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/logInRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/logInResponse")
    @RequestWrapper(localName = "logIn", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.LogIn")
    @ResponseWrapper(localName = "logInResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.LogInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean logIn(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/removeAllUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/removeAllUserResponse")
    @RequestWrapper(localName = "removeAllUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveAllUser")
    @ResponseWrapper(localName = "removeAllUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveAllUserResponse")
    public void removeAllUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/createUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.anikanov.tm.api.endpoint.User createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.anikanov.tm.api.endpoint.Role arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/updateUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ru.anikanov.tm.api.endpoint.Role arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/findAllUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/findAllUserResponse")
    @RequestWrapper(localName = "findAllUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindAllUser")
    @ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.FindAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.anikanov.tm.api.endpoint.User> findAllUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/updateUserPasswordRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/updateUserPasswordResponse")
    @RequestWrapper(localName = "updateUserPassword", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateUserPassword")
    @ResponseWrapper(localName = "updateUserPasswordResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.UpdateUserPasswordResponse")
    public void updateUserPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/removeUserRequest", output = "http://endpoint.api.tm.anikanov.ru/IUserEndPoint/removeUserResponse")
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://endpoint.api.tm.anikanov.ru/", className = "ru.anikanov.tm.api.endpoint.RemoveUserResponse")
    public void removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
